### ISSUE TITLE
Question: padding whitespace

### ISSUE THREAD

**Issue by konradzdeb** [r-lib/prettyunits#19]
Is there are a reason why you want `pretty_bytes` to return `"   1 MB"` not `"1 MB"`? IMHO, this white space at the beginning is not that useful but I see you are testing for that...

https://github.com/gaborcsardi/prettyunits/blob/596e7d1c27fc6de707b66e10db0da133bf0bb941/tests/testthat/test-bytes.r#L40-L41

**Comment by gaborcsardi** [comment]
If you are supplying a vector, then it will format each element to have the same width: 
```
pretty_bytes(c(1, 100))
#> [1] "  1 B" "100 B"
pretty_bytes(1)
#> [1] "1 B"
```

Well, at least in some cases, because it also has:
```
❯ pretty_bytes(c(1.5, 100))
[1] "1.50 B"  "100.0 B"
```

So yeah, this is definitely not ideal. Will fix now...
