### ISSUE TITLE
...prettyunits.rdb' is corrupt

### ISSUE THREAD

**Issue by schwa021** [r-lib/prettyunits#33]
I am not sure if this is a problem with "prettyunits" or "bartMan". 

I attempted to install the bartMan package using devtools. It proceeded to install prettyunits, but then threw the following error.

I tried manually installing prettyunits (new and old version from tar.gz) and got the same error

"Lazy-load database 'C:/Users/mschwartz/AppData/Local/R/win-library/4.2/prettyunits/R/prettyunits.rdb' is corrupt"

**Comment by gaborcsardi** [comment]
If you reinstall a package that is loaded, you often need to restart R.

**Comment by schwa021** [comment]
> If you reinstall a package that is loaded, you often need to restart R.

Perfect. Thank you. I thought I had done this, but apparently not. I appreciate the quick and correct answer.
